### ISSUE TITLE
Cannot read property compare of undefined

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#1001]
![image](https://user-images.githubusercontent.com/14136738/102204534-db130880-3ec1-11eb-896c-e2bfad2b8d37.png)

This comes from `MapEditPage` when attempting to perform a version check before creating an instance of the `MapEditPage` in `createInstance`.

It looks like the event `wpgmza_map_editor_init` fires, triggering the map editor to be initialized, before all the modules are loaded.

I'd recommend either changing the sequence that events fire in, or, altering the header in `map-edit-page.js` to require the `Version` module as a dependency.

8.0.29 / Pro 8.0.35, minified build, observed when attempting to use the map editor.

**Comment by DylanCodeCabin** [comment]
Marked as `stale`
