### ISSUE TITLE
Events no longer capturable

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#1009]
I'm trying to listen for the `markersplaced` event but my callback is never reached.

I can see the code which triggers this event internally is reached, but the event dispatcher doesn't pick up on any callbacks to reach in `dispatchEvent`.

Assuming `EventDispatcher` has not changed, I suspect there is some kind of inheritance issue here

**Comment by DylanCodeCabin** [comment]
Marked as `stale` - Modules recently built using this event, should be all good in V9 at least, otherwise, it will be reopened later if need be.
