### ISSUE TITLE
ScriptLoader Error Message Breaks REST request preventing maps from loading markers.

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1019]
@DylanCodeCabin 

Environment:
PHP Version: 7.4.30
WP Version: 6.0
Build Code: B.9.0.1::P.8.1.20::L.G.D
Internal Engine: Legacy
Map Engine: Google Maps
Developer Mode: Enabled

This ScriptLoader error message breaks REST requests:

- https://github.com/CodeCabin/wp-google-maps/blob/c851c53ec11a4eb0b136f1249234afb4f69943ac/includes/class.script-loader.php#L306-L325

Perhaps check for REST requests before outputting the message.

**Comment by shazahm1** [comment]
Just dropping by to say this still occurs with 9.0.2.

**Comment by shazahm1** [comment]
Tweaking the code to be this; adding a rest request check fixes the error notice breaking the rest requests while still displaying the error notice.

A more thorough utility function, like this one, would be more useful long term:

- https://wordpress.stackexchange.com/a/317041/59053

``` PHP
if(!ScriptLoader::$dependencyErrorDisplayed)
{
	if ( ! ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) {

		?>
		<div class="notice notice-error">
			<p>
				WP Go Maps: Build failed. Dumping unresolved dependencies
			</p>
			
			<?php
				echo "<pre>";
				foreach($unresolvedDependencyHandles as $handle => $reference)
				{
					echo "$handle (in " . implode(', ', $this->dependenciesByHandle[$handle]) . ")\r\n";
					echo "Requires:\r\n" . implode("\r\n", $reference);
					echo "\r\n";
				}
				echo "</pre>";
			?>
			
			<p>
				Are you debugging or developing WP Go Maps? If not, please disable developer mode in Maps &rarr; Settings &rarr; Advanced to remove this notice.
			</p>
		</div>
		<?php
	}
	
	ScriptLoader::$dependencyErrorDisplayed = true;
}
```

**Comment by DylanCodeCabin** [comment]
@shazahm1 Thank you for the adjusted dependency code, that should be quite helpful. We are actually planning a long term rebuild of that module. 

With that said, as an interim solution to the major version mismatch issues, I will go ahead and log this solution in our internal repos for consideration in the near future. This would at least avoid some of the larger issues with the version mismatch.
