### ISSUE TITLE
jQuery.isNumeric() is deprecated

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1024]
As the subject states, a couple of dozen instances within WPGM and Pro use this deprecated jQuery function.

**Comment by DylanCodeCabin** [comment]
Thanks @shazahm1 -> We'll get these sorted asap, something we've been meaning to take stock of for a little while now, but should get a bit more priority soon!

**Comment by DylanCodeCabin** [comment]
These have been replaced with an internal counterpart `WPGMZA.isNumeric` instead, to help standardize the code base, and reduce the reliance on the jQuery counterpart. 

Works the same way, but should resolve any dependency issues in that respect.
