### ISSUE TITLE
jQuery.fn.bind() is deprecated

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1025]
As the subject states, both WPGM and Pro use this deprecated jQuery function.

**Comment by DylanCodeCabin** [comment]
Thanks @shazahm1 -> It's been added to the internal repo and is on the next sprint list!

**Comment by DylanCodeCabin** [comment]
These have been replaced, where they are present in our core files. 

There are some cases where a library may need to be updated to reduce/remove the use of `.bind` -> These will be resolved as part of a later library update sprint. 

With that said, most of the core bind calls have been replaced.
