### ISSUE TITLE
Plugin scripts are loaded on non plugin admin pages.

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1027]
When in the WP admin, a couple of scripts are loaded on pages other than WPGM admin pages. Please see attached screenshot.

![wpgm-assets](https://user-images.githubusercontent.com/1185008/176520863-65f52a40-b659-4125-835a-8df0f70bb278.png)

**Comment by DylanCodeCabin** [comment]
@shazahm1 Ah yes, these are some of the "legacy" files which load outside of their scope. We've been trying to reduce these as we go, but these slipped through. 

I am making a note of this on the internal repo as well and we'll get it sorted! Thanks for the report!

**Comment by DylanCodeCabin** [comment]
V9.0.6 will no longer load these:
- exif.js
- import-export-page.js 
 

For the moment, `wpgmza_data.js` will need to remain while we consider the implications of altering this as it is being user for localization. It's slated for deprecation, but this is not ready at the moment.
