### ISSUE TITLE
ReflectionException in ReflectionClass::__construct

### ISSUE THREAD

**Issue by AmitT** [CodeCabin/wp-google-maps#1029]
on file: `includes/class.rest-api.php` on line 957
`$reflection = new \ReflectionClass($class);`
**ReflectionException**
Class "\" does not exist

WP Go Maps 9.0.5
WP 6.0
PHP 8.1.4
Linux

**Comment by DylanCodeCabin** [comment]
@AmitT Thank you for reporting this issue! 

We will introduce a patch to this in our next update! (9.0.6)
