### ISSUE TITLE
[Feature request] don't remove duplicate markers in different maps

### ISSUE THREAD

**Issue by nicoletta-maia** [CodeCabin/wp-google-maps#1039]
_Remove duplicate markers_ button deletes markers even if they belong to different maps; in our website several maps have some markers in common and we would not want them to be considered duplicates. Could you consider this change?

I would suggest changing [here](https://github.com/CodeCabin/wp-google-maps/blob/master/includes/class.rest-api.php#L767) and [here](https://github.com/CodeCabin/wp-google-maps/blob/master/includes/class.rest-api.php#L773) the _GROUP BY_ clause to: `GROUP BY map_id, lat, lng, address, title, link, description`

**Comment by DylanCodeCabin** [comment]
@nicoletta-maia Thank you for bringing this to our attention! 

I can definitely see how this additional condition would be helpful. Originally the logic was developed to remove duplicates, regardless of the Map they belong to, but in hindsight, we should have thought about this combination as well. 

I have flagged this as a bug, and it will be resolved in our next update.

**Comment by DylanCodeCabin** [comment]
This has been released in a pre-release, which will be deployed in the next week
