### ISSUE TITLE
Pro: Categories in the drop down still display in order of ID instead of alphabetically by title. 

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#105]

**Comment by NickDuncanZA** [comment]
$sql = "SELECT * FROM `$wpgmza_tblname_category_maps` LEFT JOIN `$wpgmza_tblname_categories` ON $wpgmza_tblname_category_maps.cat_id = $wpgmza_tblname_categories.id WHERE `map_id` = '$map_id' OR `map_id` = '0' ORDER BY `category_name` ASC";
