### ISSUE TITLE
Image resizing dimensions are ignored (even when dimensions are entered in settings page)

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#106]

**Comment by NickDuncanZA** [comment]
Cannot replicate. It seems to take the width and height on my side

**Comment by DylanCodeCabin** [comment]
Replicated this issue -> When there are multiple maps on a page. 

For some reason the 'px' gets appended multiple times. I believe it is because we are appending it not only when we save the variable, but also when we output the date -> Debugging now. Solution will follow

**Comment by DylanCodeCabin** [comment]
Solution here

**Comment by DylanCodeCabin** [comment]
I have reopened this issue, as it is a confirmed core.js bug

This is also the cause for issue (14) https://github.com/CodeCabin/wp-google-maps/issues/14 in VGM

And I believe this is the cause of issue 165 -> https://github.com/CodeCabin/wp-google-maps/issues/165

**Comment by PerryRylance** [comment]
Can this be closed?
