### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by kipperthekoolbus** [CodeCabin/wp-google-maps#1064]
1) Can users who visit the page enter markers? and if they do, can they sit until approved?

2) Can markers be synced from a google account with markers? Add markers from account, anytime one added to site or google maps app they sync up?

**Comment by DylanCodeCabin** [comment]
Hi @kipperthekoolbus 

Thank you for getting in touch, we appreciate your time. 

Please find my responses below: 
1. Yes, we have a dedicated add-on for this called the Visitor Generated Markers add-on. It allows users to submit markers to your map from the frontend. You can hold them for approval, or auto approve them, using various settings available. You can learn more about it here: https://www.wpgmaps.com/visitor-generated-markers-add-on/ 
2. Unfortunately, this is not currently supported. The closest feature that we have available (in our Pro add-on) is scheduled imports from a Google Sheet. This means you can set up a Google Sheet, and import all the data from that sheet, on a schedule (for example once per day/week), and replace any existing markers

I hope that helps.

**Comment by DylanCodeCabin** [comment]
Closing this thread as I haven't heard back. If you need anything else, please do feel free to reach out to us on our website: 
- https://www.wpgmaps.com/contact-us/
