### ISSUE TITLE
Use two fingers to move the map issue

### ISSUE THREAD

**Issue by ShinobivsDragonNinja** [CodeCabin/wp-google-maps#1073]
How do I remove the "Use two fingers to move the map" ? Please see attachment.

https://github.com/CodeCabin/wp-google-maps/assets/102356922/ea2b5b75-dd7e-44e4-b777-ec3cc4079050

**Comment by DylanCodeCabin** [comment]
Hi @ShinobivsDragonNinja , 

Thank you for reaching out, we do appreciate your time. 

The specific message is controlled by the "greedy gesture" system in the setting area of the plugin, however, it is not being displayed the way it should. It should only show when the user touches the map while scrolling down the page, fading in and back out when the user is no longer touching the map. 

Could I ask you to share a link to this page with us that is publicly accessible? I would then be able to run a few more tests to confirm why things are not showing as they should. Once we have this resolved, you can still disable the two finger touch system if you prefer, but I would like to ensure your site is running properly.

**Comment by DylanCodeCabin** [comment]
Hey @ShinobivsDragonNinja - Thank you for that, I've had a look and I can see quite a few of our styles are being removed. 

I noticed you are using LiteSpeed cache, and you may have the option to "remove unused CSS" enabled. This causes issues with out plugin as most of our elements are loaded later, and LiteSpeed cannot detect them. 

This results in some CSS being removed, which in case is removing the styles associated to map controls, and the overlay I mentioned. 

I believe you can resolve this quite easily by navigating to LiteSpeed > Page Optimization > CSS Settings > By disabling "Generate UCSS" if it is currently enabled.

**Comment by ShinobivsDragonNinja** [comment]
I can confirm, disabling Generate UCSS fixed it 👍

**Comment by DylanCodeCabin** [comment]
Glad to hear that helped @ShinobivsDragonNinja - If you still prefer to disable the two-finger panning, you can enable greedy gesture controls in the settings area, it should be located under **Maps > Settings** > Within the first tab (General)

Have a nice day
