### ISSUE TITLE
Pro: Category checkbox/dropdown option doesn't take effect in store locator

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#108]
Current functionality uses the map data variable 'filterbycat' which returns 1 or 0. 

This needs to be changed to use the global settings instead of the map settings

**Comment by JarrydLong** [comment]
Version 6 only. 

Function: wpgmaps_sl_user_output_pro

Needs to use $wpgmza_settings = get_option("WPGMZA_OTHER_SETTINGS"); for that field

**Comment by NickDuncanZA** [comment]
Fixed in version 6.05
