### ISSUE TITLE
Change Store Locator Labels to improve user flow

### ISSUE THREAD

**Issue by NathanM101** [CodeCabin/wp-google-maps#115]
Several clients have stated that the Store Locator (with the Category Filter options enabled) does not work correctly.

They assume that the Store Locator allows you to filter the results of your search to only display that category on the map.

A quick solution, might be to just change the Filter By label to say something like - Filter Search Results etc and then move the Filter By options below the Search button.

Alternatively, the filter can be applied to the Store Locator so it does only show that category on the map after clicking search.

**Comment by NickDuncanZA** [comment]
This is related to a custom job. Closing ticket
