### ISSUE TITLE
Pro: When selecting the red/yellow gradient for heatmaps, a JavaScript error is thrown on the map

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#117]
Done some testing, it looks like when clicking on the red/green gradient, a value of '1' is set. This value seems to be getting parsed via JSON and treated like the RBG colors for the blue gradient, instead of just being stored and then checking on the map if the value is 1, then not to try change the gradient.

**Comment by PerryRylance** [comment]
Cannot reproduce in Pro 6, 7 or 8
