### ISSUE TITLE
Critical: Google Maps API version 3.23 is being retired - all calls should default to either 3.24 or experimental version.

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#119]

**Comment by NathanM101** [comment]
Going to Basic Line 517 and altering existing code to include 3.23 in the IF statement -

if (isset($wpgmza_settings['wpgmza_api_version']) && ($wpgmza_settings['wpgmza_api_version'] == "3.14" || $wpgmza_settings['wpgmza_api_version'] == "3.15" || $wpgmza_settings['wpgmza_api_version'] = "3.23")) {
            $wpgmza_settings['wpgmza_api_version'] = "3.24"; }

Going to Pro line 789 and altering the existing code like above -

if (isset($wpgmza_settings['wpgmza_api_version']) && ($wpgmza_settings['wpgmza_api_version'] == "3.14" || $wpgmza_settings['wpgmza_api_version'] == "3.15" || $wpgmza_settings['wpgmza_api_version'] = "3.23")) { $wpgmza_settings['wpgmza_api_version'] = "3.24"; }

This defaults the API call to 3.24 easily.
