### ISSUE TITLE
Show category title for marker listing

### ISSUE THREAD

**Issue by andrewlimaza** [CodeCabin/wp-google-maps#124]
Hey,

Would be great if we could show the category title and what markers belong to that category in a marker list style.

For example -

'Category title 1'
 marker 1 belongs to this category with link
 marker 5 belongs to this category with link
 marker 7 belongs to this category with link
'Category title 2'
 marker 4 belongs to this category with link
 marker 6 belongs to this category with link
 marker 8 belongs to this category with link

etc.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
