### ISSUE TITLE
Additional workaround for multiple Google Maps API calls

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#129]
Change Google Maps API calls from

`<script type="text/javascript">
 var gmapsJsHost = (("https:" == document.location.protocol) ? "https://&quot; : "http://&quot;);
 var wpgmza_api_key = '<?php echo get_option( 'wpgmza_google_maps_api_key' ); ?>';
 document.write(unescape("%3Cscript src='" + gmapsJsHost + "maps.google.com/maps/api/js?<?php echo $api_version_string; ?>key="+wpgmza_api_key+"&language=<?php echo get_locale(); ?>&libraries=places,visualization' type='text/javascript'%3E%3C/script%3E"));
 </script>`

to 

```
        <script type="text/javascript">
            var gmapsJsHost = (("https:" == document.location.protocol) ? "https://&quot; : "http://&quot;);
            var wpgmza_api_key = '<?php echo get_option( 'wpgmza_google_maps_api_key' ); ?>';
          if( typeof google === 'undefined' ){
               document.write(unescape("%3Cscript src='" + gmapsJsHost + "maps.google.com/maps/api/js?<?php echo $api_version_string; ?>key="+wpgmza_api_key+"&language=<?php echo get_locale(); ?>&libraries=places,visualization' type='text/javascript'%3E%3C/script%3E"));
          }
        </script>
```

**Comment by NickDuncanZA** [comment]
We should use
`if (typeof google === 'object' && typeof google.maps === 'object') { } else { /* load API */ }`

**Comment by NickDuncanZA** [comment]
Moving this out to the next milestone as this will need some solid testing
