### ISSUE TITLE
(PRO) Resetting directions keeps old route data

### ISSUE THREAD

**Issue by NathanM101** [CodeCabin/wp-google-maps#13]
Resetting directions removes values, but keeps locations in memory and adds them as an additional point to the map, as well as adds the new locations directions to the old ones below it in the same panel.

**Comment by NickDuncanZA** [comment]
Wow thats actually pretty cool.. We made waypoints by mistake ;)
Nonetheless I shall fix it :+1:

**Comment by NickDuncanZA** [comment]
fixed in 6.3.14
