### ISSUE TITLE
Conduct Store Locator search on pageload (via GET)

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#132]
#29901

**Comment by WAMH** [comment]
Hello :)
Ideally, this would iterate a few options like:

if ( user location in enabled and allowed ) { search user location }
else if ( can we store the last search somewhere in db or a cookie? ) { search last search }
else if ( default location is set in config ) { search that }
else { fallback on empty map }

Thanks for the neat plugin!

**Comment by DylanCodeCabin** [comment]
Closed as `stale` -> Introduced in V9, also allows separation into a new page
