### ISSUE TITLE
(VGM) Uploaded image does not restrict to global image resizing

### ISSUE THREAD

**Issue by NathanM101** [CodeCabin/wp-google-maps#14]
In the VGM any image that is uploaded to the marker is not restricted to the size restrictions set in the admin area, it displays full size after a search with the Store Locator ( 22337 ).

**Comment by NickDuncanZA** [comment]
@DylanCodeCabin suggestions on the way forward for this?

**Comment by DylanCodeCabin** [comment]
Testing this now to find a solution -> This issue may/may not be related to issue 106 (https://github.com/CodeCabin/wp-google-maps/issues/106) - Will test and confirm

**Comment by DylanCodeCabin** [comment]
CONFIRMED -> This is related to issue 106 (https://github.com/CodeCabin/wp-google-maps/issues/106) 

As the 'px' is being appended (ex: pxpxpxpx)

The solution provided in issues 106 (https://github.com/CodeCabin/wp-google-maps/issues/106) will resolve this VGM issue. As this is actually a core.js bug

**Comment by PerryRylance** [comment]
Can we go ahead and close this issue?
