### ISSUE TITLE
Directions box strings do not translate

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#140]
All strings are available in the .po file, however none translate on the page.

**Comment by JarrydLong** [comment]
Further debugging as found that the current language files on WordPress.org don't contain the translated strings for the directions box. Translating these are in progress

**Comment by JarrydLong** [comment]
WordPress 4.6+ takes preference over the language files provided by WordPress.org

The directions box strings are all in the Pro version - as a result are not available in the .po file on WordPress.org

Suggestion: Create a languages folder, add a `wp-google-maps-pro` text domain in the Pro version to accommodate the untranslated strings in the Pro version

**Comment by PerryRylance** [comment]
Would changing the text domain not break the strings that are in the basic version?
