### ISSUE TITLE
Potential plugin conflict with iThemes security

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#143]
As per forum post https://wordpress.org/support/topic/settings-lowest-level-of-access-to-the-map-editor-access-denied/#post-8190550

Administrators cannot access the map editor if the user role allows for a lower level of access. 

Potentially site specific, however needs to be tested further to try and replicate.

**Comment by PerryRylance** [comment]
Couldn't reproduce this issue
