### ISSUE TITLE
Ability to override map width and height in the shortcode attributes

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#147]

**Comment by NickDuncanZA** [comment]
Ticket 33216

**Comment by brentschneider** [comment]
Would love to set the height within the short code, is this still on the radar?  

**Use case:**
Setting the height within the short code for use with responsive break points.

&lt;div class=&quot;visible-sm&quot;&gt; **[wpgmza id=&quot;1&quot; zoom=&quot;11&quot; _height=&quot;300px&quot;_]** &lt;/div&gt; 
&lt;div class=&quot;visible-md hidden-lg&quot;&gt; **[wpgmza id=&quot;1&quot; zoom=&quot;10&quot; _height=&quot;600px&quot;_]** &lt;/div&gt; 
&lt;div class=&quot;visible-lg&quot;&gt; **[wpgmza id=&quot;1&quot; zoom=&quot;9&quot; _height=&quot;100%&quot;_]** &lt;/div&gt;

**Comment by DylanCodeCabin** [comment]
Closed as `stale` -> Should be supported in upcoming and partially by current releases
