### ISSUE TITLE
JavaScript Conflict with Search by Algolia Plugin (Autocomplete)

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-google-maps#163]
## Reference

**Support Forums**: http://www.wpgmaps.com/forums/topic/autocomplete-javascript-variable-conflict/
**Algolia GitHub Issue**: https://github.com/algolia/algoliasearch-wordpress/issues/372

Customer reports that there is a JavaScript conflict with [Search by Algolia](https://wordpress.org/plugins/search-by-algolia-instant-relevant-results/) plugin. Apparently, both Algolia and WP Google Maps were registering the same variable on `window: autocomplete`. 

I visited the page referenced in the Algolia GitHub issue, but the console did not reflect any issue with `window: autocomplete`. Still it might be wise to ensure we check for conflicts here.

**Comment by JarrydLong** [comment]
All autocomplete functions are assigned the variable `autocomplete` - perhaps we should change it to something like `wpgmza_autocomplete` to prevent this from happening again

**Comment by rayrutjes** [comment]
Same for us, we use the `autocomplete` variable in our Algolia plugin, but we indeed need to change this to make it less subject to conflicts ;)

**Comment by PerryRylance** [comment]
We're moving away from the global scope, this has gone in Pro 8
