### ISSUE TITLE
Ability to make iFrames (Such as Youtube videos) responsive 

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#168]
Currently, Youtube videos aren't responsive at the moment as they require px values. 

A suggestion was made under http://www.wpgmaps.com/forums/topic/easier-and-responsive-video-embeds-in-info-windows/ to putting the iFrames in a div and use some css ( you can generate responsive iframe embed code at embedresponsively .com).

**Comment by PerryRylance** [comment]
This is an issue outside of our plugin
