### ISSUE TITLE
Autocomplete Store Locator -> Basic Version

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#172]
Autocomplete for the store locator is not working as intended on the front-end.

As seen in forum topic: http://www.wpgmaps.com/forums/topic/store-locator-autocomplete-field-search-like-demo/

This should be resolved in the next update

**Comment by DylanCodeCabin** [comment]
We need to add `&libraries=places` to our API calls.

**Comment by PerryRylance** [comment]
Places API has been present for quite some time now
