### ISSUE TITLE
Provide additional support for Ajax loaded themes

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#175]
Some Ajax loaded themes don't run the header/footer like a standard page load, so scripts don't get loaded, only the HTML for the shortcode. 

This has been brought up in this topic: https://wordpress.org/support/topic/ajax-powered-theme/

_The page loads using JS like this:_

```
var $scripts = $ajaxResponse.find('#content script');

$scripts.each(function() {
var scriptText = $(this).html();
if ('' !== scriptText) {
    var script = document.createElement('script'),
        textNode = document.createTextNode(scriptText);
    script.appendChild(textNode);
    contentNode.appendChild(script);
} else {
    $.getScript($(this).attr('src'));
}
});
```

**Comment by PerryRylance** [comment]
Aiming for full AJAX support by version 9.0.0

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
