### ISSUE TITLE
Allow shortcodes in markers

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#179]
This currently will only work with the XML File method due to the fact that we cannot cal _do_shortcode at the moment when we localize the variables as the localization is taking place WITHIN a do_shortcode itself. This results in a "not found" issue for most shortcodes. To fix this we will have to move the localizing or the markers to outside the tag_pro function, and perhaps localize it in the head and make it a dependency of jQuery.

**Comment by PerryRylance** [comment]
Fully supported as of v7
