### ISSUE TITLE
Remove Reference to TimThumb in Carousel Settings

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-google-maps#182]
**WordPress Dashboard → Settings → Marker Listing → Carousel Marker Listing** still refers to TimThumb in the *Resize Images with Timthumb* setting. Suggest that terminology be changed since TimThumb is no longer [being used](https://www.wpgmaps.com/were-phasing-out-timthumb/).

**Comment by NickDuncanZA** [comment]
@JarrydLong please make sure this is completely removed from the pro version and then check to see that the images resize correctly in the Carousel
