### ISSUE TITLE
Adjust Structure of 'wpgmaps_plugurl' or encode it to prevent bots from detecting this URL

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#184]
As seen here: 

`
Google Webmaster Tools complains about 403 Forbidden Errors because the 
plugin links to /wp-content/plugins/wp-google-maps/

On every page where a map is included the following can be found inside 
a script:

 wpgmaps_plugurl='http://www.dublin.de/wp-content/plugins/wp-google-maps/'; 
The Google Bot is trying to go to that url for whatever reason. If that 
link wouldn't be there crawling would be more effective because 
everytime the bot visits your page he just follows a certain (unknown) 
number of internal links until he leaves the page. So this url is taking 
place where another internal link would be visited by the bot. There are 
ways how you can split that url so it is not visible to the bot.
`

The user suggests maybe breaking the URL up into segments (perhaps an array) to prevent detection. 

Alternatively we could look at encoding it and then simply decoding it during use as a variable.

**Comment by PerryRylance** [comment]
This variable is no longer present
