### ISSUE TITLE
Google Maps API Call - incorrect forceful locale setting

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#191]
We are forcing the locale of the WP installation to be pushed to the API call when Google Maps API should handle this automatically.

**Comment by JarrydLong** [comment]
@NickDuncanZA The only way we can change the map's language is by adding the `language` attribute in the URL (https://developers.google.com/maps/documentation/javascript/localization). 

Currently, WP gives a locale value of (for example) _en_EN_, while the Google Maps API only requires _en_

Would it not be better to just replace the given _en_EN_ with _en_ ?
