### ISSUE TITLE
Custom Default Marker doesn't show in the 'Add Marker' box next to the map

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#194]
When using a custom default marker, the default red pin shows up in the panel when adding a marker (below):

![image](https://cloud.githubusercontent.com/assets/8989542/21090833/1a6472ac-c04b-11e6-8acf-e0a115ccc943.png)

The new custom default marker is added to the map correctly. The above red pin still showing creates some confusion for users though as their new custom marker should show instead.

**Comment by PerryRylance** [comment]
Solved in Pro 6 and above
