### ISSUE TITLE
Failover for "adding" when adding a marker and there is a JS error

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#195]

**Comment by NickDuncanZA** [comment]
Chat to me about this when you get to this :D

**Comment by PerryRylance** [comment]
Well, it seems the event listeners will fire regardless of whether an exception is thrown in a previous one

jQuery seems to queue the exception and then throw it after firing all the listeners,
Even the native event handlers will still fire if there's an exception

Off the top of my head the only scenario that the above situation could happen in is if the customer is using a merge minify plugin and then plugin X throws an exception in the global scope, in which case our event listener is never bound, in fact none of our code is even reached, so I'm not sure if there's a way to even implement a failback in this case

Short or en-queuing our scripts with a higher priority, there's not much I can think to do to solve this one, if you can find any examples of it though I can tell you definitively!
