### ISSUE TITLE
Ability to change gesture input

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#198]
Have a look here:

https://developers.google.com/maps/documentation/javascript/interaction

**Comment by andrewlimaza** [comment]
I was just about to create an issue for it.

Here's another link - 
https://maps-apis.googleblog.com/2016/11/smart-scrolling-comes-to-mobile-web-maps.html

Do we just need to add this to the initmap call on the frontend?
