### ISSUE TITLE
Local info window settings aren't effective

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#206]
Selecting an info window in the map editor doesn't show up on the map - most likely caused by the global setting overriding it in the settings page.

**Comment by JarrydLong** [comment]
![image](https://cloud.githubusercontent.com/assets/8989542/22928925/9d9aeec8-f2c1-11e6-8a5a-9a6717f903d1.png)

Both info windows show up when opening a marker from a marker listing item

**Comment by PerryRylance** [comment]
In addition, "start with info window open" is not respected with the custom info windows

**Comment by PerryRylance** [comment]
Should be fixed when my upcoming pull request is accepted

**Comment by PerryRylance** [comment]
Fixed in #215
