### ISSUE TITLE
Show/hide POI on the map

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#216]
See https://developers.google.com/maps/documentation/javascript/examples/hiding-features

For both the basic and the pro

**Comment by PerryRylance** [comment]
I've done this in the past,

Did you want this as a field on the backend?

**Comment by NickDuncanZA** [comment]
Yes, perhaps in the theme tab?

**Comment by PerryRylance** [comment]
Should be ready to go when my upcoming pull request is accepted

**Comment by PerryRylance** [comment]
Fixed in #94 (other repo) and #215
