### ISSUE TITLE
Fresh install test

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#220]
Please create a fresh WP installation with Debug enabled and run the basic version for the first time. Please identify any usability issues, errors or warnings that come up

**Comment by PerryRylance** [comment]
- I am thanked for my feedback, even though I didn't leave any (I just clicked into the box, didn't type anything)
- I think the radio buttons should be auto-selected when you click into feedback text fields

**Comment by PerryRylance** [comment]
Perfect other than that

**Comment by PerryRylance** [comment]
Actually this is just me being daft, I can see now there's a separate button for skip intro and create map, and a button after you scroll down to submit feedback and continue

Maybe another button for dafties might be in order, I thought about making the text fields required when their respective radios are selected, but this is such a small thing I'm going to save it for V7 and leave it for now
