### ISSUE TITLE
Fit bounds to zone

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#235]
See

http://popotes.org/trouve

Try your village, town, county, etc. the map will fit the bounds of the zone you've put in (as opposed to just centering on it)

**Comment by PerryRylance** [comment]
I've just discovered that the nominatim (OSM recommended) geocoder returns a bounding box on queries, this might be worth using in this instance

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
