### ISSUE TITLE
SQL Query option in the admin to get specific marker data from the database

### ISSUE THREAD

**Issue by NathanM101** [CodeCabin/wp-google-maps#265]
It would be nice to open up an interface where you could do SQL-queries and get the result in a list

**Comment by PerryRylance** [comment]
Is this a customer suggestion?

Just wondering what kind of queries our users might want to run,

Exposing the database can be very dangerous. If the user doesn't have phpMyAdmin (and know how to use it) then it might not be ideal. A JSON endpoint would be a safer solution
