### ISSUE TITLE
Ability to bypass geocoding when adding marker

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#280]
I've had this request before, we're definitely going to want to implement this if we're using nominatim as our geocoder in V7, it's nowhere near as accurate as Googles

Please implement this as a checkbox in the marker add/edit panel

A nice compliment to this would be a button so they can make the marker draggable so they can position it precisely, then save it without the geocoder kicking in and moving the marker back

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
