### ISSUE TITLE
Marker Export CSV File Is complicated to work with - V7

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#305]
The current 'settings' of a marker are being stored as:

`{"animation":"0","infoopen":"0","DataTables_Table_0_length":"10","retina":false}`

In the past we've had clients who feel that the current CSV files are already a challenge to work with (In Version 6) - this will just add to the problem due to poor formatting on the user's part

**Comment by PerryRylance** [comment]
There are many, many advantages of JSON over CSV that I won't go into right here (ask me if you're interested), how about catching parse errors and issuing the user with a warning if the formatting is bad?

**Comment by JarrydLong** [comment]
I agree, just looking at this from a usability perspective. Some people battled with 13 columns, now there will be less columns but more curly brackets

**Comment by PerryRylance** [comment]
I've changed the importer to support arbitrary columns - any columns in the CSV that don't have a corresponding column in the DB will be stored in the settings object

I'm about to add an option to the exporter to "unroll" the settings object into individual columns when exporting too
