### ISSUE TITLE
User should be given an option to click on a marker and edit it or just open the info window - V7

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#306]
In the map editor

- Currently clicking on a marker will automatically edit it
- May cause confusion with users as they could just be clicking on a marker to identify it

**Comment by PerryRylance** [comment]
What behaviour would you suggest as an alternative? Double click maybe?

**Comment by JarrydLong** [comment]
Either a double click, or an option in the settings page to choose between 'Clicking and editing' or 'Only Clicking'
