### ISSUE TITLE
Labels for polygons and polylines

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#324]
See

https://stackoverflow.com/questions/1203135/what-is-the-fastest-way-to-find-the-visual-center-of-an-irregularly-shaped-pol

For polygons

See bezier.js for polylines

**Comment by KZeni** [comment]
Just want to give a mention to https://www.wpgmaps.com/forums/topic/feature-proposal-add-ability-to-show-text-labels-within-polygons/ here since I have working code accomplishing this task (though the flexibility/user-friendliness of this hasn't been fleshed out.)

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - We have developed this in V9
