### ISSUE TITLE
Markers set to open on hover should automatically default to a 'click' event when using on a mobile device

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#325]
Markers that are to open on hover don't open at all on mobile devices

**Comment by PerryRylance** [comment]
This *shouldn't* be an issue as mobile browsers treat click events as hover events, at least in the plain DOM. This will need to be checked before making changes.

**Comment by DylanCodeCabin** [comment]
We have received another report of this. So we will need to look into this.

**Comment by PerryRylance** [comment]
Practically all browsers will fire "hover" when the user presses on the screen for compatibility reasons,

I'm not sure what circumstances this was reported in but in any case, I couldn't reproduce this on Android / Chrome
