### ISSUE TITLE
Errors with wpgmza_get_allowed_tags() and wpgmza_track_usage()

### ISSUE THREAD

**Issue by Tanmccuin** [CodeCabin/wp-google-maps#346]
Running into a persistent error that's causing some 500 errors in wp-admin - is there an issue with redeclaration when moving between dev/live etc?

```
Cannot redeclare wpgmza_get_allowed_tags() (previously declared in /srv/bindings/fb9a862b08cc467397e544b17ad4f45d/code/wp-content/plugins/wp-google-maps-pro/wp-google-maps-pro.php:8996)wp-content/plugins/wp-google-maps-pro/wp-google-maps-pro.php:89968 minutes ago

Cannot redeclare wpgmza_track_usage() (previously declared in /srv/bindings/fb9a862b08cc467397e544b17ad4f45d/code/wp-content/plugins/wp-google-maps/wpGoogleMaps.php:6537)wp-content/plugins/wp-google-maps/wpGoogleMaps.php:65379 minutes ago
```

**Comment by NickDuncanZA** [comment]
Thank you for bringing this up @Tanmccuin ! This is the first I've heard of this.
We'll get right on it!
@JarrydLong please can you look into this and get a new version up ASAP?

**Comment by JarrydLong** [comment]
Hi @Tanmccuin, I've cross referenced the code in our latest versions as well as run the plugin and checked the error logs however I was unable to replicate this on my side. 

Were either of the plugin files duplicated and activated at all during the process of the site being moved from staging to production? 

May I suggest removing the current wp-google-maps and wp-google-maps-pro folders and re-installing the plugin on the site, and let me know if the issue persists?

**Comment by Tanmccuin** [comment]
I can have a look - to confirm, both plugins should be installed and active yes? 

Also if it's any help - the site (& plugins) are hosted through Pantheon.io - so as far as duplication goes, there are duplications in so much that pantheon uses versioning and multiple versions of plugins exist for each version/branch etc.

**Comment by JarrydLong** [comment]
Hi @Tanmccuin 

Thanks so much for your feedback. Yes, both plugins should be installed and active. 

The duplicates in terms of versioning shouldn't be an issue provided that no more than one of each is active on the site at any given time. 

Please let me know your findings after uninstalling/reinstalling?

**Comment by PerryRylance** [comment]
This function is only present once in Pro 6 - 8, this is no longer an issue.
