### ISSUE TITLE
Safari 11 > Map is broken and doesn't display any content 

### ISSUE THREAD

**Issue by aamorozov** [CodeCabin/wp-google-maps#356]
The issue appeared on a few of our wordpress websites that currently use this plugin. The map is also broken on the plugin's website at:

https://www.wpgmaps.com/

#### Here is the console error 
![screen shot 2017-09-25 at 12 52 49 pm](https://user-images.githubusercontent.com/10227658/30820634-7d431202-a1f0-11e7-9b0f-ada4d5dd013e.png)

#### UI. Expected behavior(ss from Chrome)
![screen shot 2017-09-25 at 12 53 31 pm](https://user-images.githubusercontent.com/10227658/30820670-9df97716-a1f0-11e7-989d-dc7c7ac38dc6.png)

#### Actual behavior(in Safari 11)
![screen shot 2017-09-25 at 12 53 41 pm](https://user-images.githubusercontent.com/10227658/30820693-b2557854-a1f0-11e7-8671-422e2d6af70f.png)

**Comment by NickDuncanZA** [comment]
Hi @aamorozov 
Thank you for bringing this up. I am in the process of updating to Safari 11 now and will look into this as a matter of urgency! Thank you again!
