### ISSUE TITLE
Separate shortcodes for map components

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#363]
Allow users to place components (eg directions box, store locator and marker listing) arbitrarily with separate shortcodes for those components

This may not be possible, so please test thoroughly. It may be the case that the components would have to be in map divs so that JS selectors still work. They would need a reference to the *other* shortcode elements map object in order to be linked.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
