### ISSUE TITLE
Plugin always loads (v6)

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#379]
See below, these files load regardless of whether there is a shortcode on the page or not

![image](https://user-images.githubusercontent.com/14136738/33257433-104866e0-d34e-11e7-9eb8-db9f759ba800.png)

**Comment by NickDuncanZA** [comment]
This is a pro bug. Will fix now.

**Comment by NickDuncanZA** [comment]
fixed. Pro 6.19
