### ISSUE TITLE
Tabs break info window starts open

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#545]
The tab wordaround causes the entire map to reload and the infowindow doesn't open a second time

**Comment by NickDuncanZA** [comment]
Is this in the settings page or the map editor?

**Comment by NickDuncanZA** [comment]
I also don't understand the title: "Tabs break info window starts open" 😂

**Comment by andtrev** [comment]
I'm not sure what this means, can you point in the right direction?

**Comment by PerryRylance** [comment]
Sorry for not making this clearer:

- Make a map with a marker, set the marker to have infowindow starts open
- Set up a page with tabs on it and add the map to a tab that doesn't start active
- Use the tab workaround from our documentation

Expected behaviour:
- When clicking the tab, the map will open with the infowindow open over the marker

Observed behaviour:
- The tab workaround causes the map to reload, this causes the infowindow to be closed (as it's no longer on the 1st load)

**Comment by andtrev** [comment]
I don't see this behavior, I tried with all different styles of InfoWindows, each time the marker set to InfoWindow open by default and always loads open even after the map reloads.

Unless I'm mistaking InfoWindow open by default for some other setting infowindow starts open?

All this code does is run InitMap(mapid,'all',false); and even when I just run it in the console to reload the map it still works fine.

**Comment by PerryRylance** [comment]
This has been fixed as of 7.11.00 which uses marker filtering and toggles visibility rather than re-loading the entire map
