### ISSUE TITLE
Add links to relevant documentation all over UI

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#547]
This could be implemented using a help cursor like in some native windows apps. I haven't seen this lately but it used to be popular and it's very intuative to use.

We could add data-documentation-href attributes to elements, clicking them with the help cursor could AJAX load the documentation and show it in a popup, with the option to open the documentation in a new tab.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
