### ISSUE TITLE
Rename Norwegian translation files

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#550]
"I'm not entirely sure of what you mean by no_NO being traditional. 

However, renaming the *no_NO-language file to nb_NO did the trick (and both the maps and the map settings in wordpress are now shown in Norwegian (however, the translation need some work, but this I will adapt with my own language file for mye purposes..).

-The b in "nb" is probably for "bokmål" which is the standard norwegian - and by far the most used "dialect"/form, as opposed to nynorsk or "new norwegian". "

**Comment by NickDuncanZA** [comment]
done
