### ISSUE TITLE
Polygon / polyline data field

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#553]
Users frequently corrupt their data, the data is injected into JS, syntax errors are caused if you enter the data incorrectly

Possible solutions

a) Don't expose this data to the user at all

b) Change the way the data is outputted instead of injecting it directly into JS (this way lies syntax errors)

c) Parse the numbers using a regex in PHP and output them in a predictable way

d) Change the text field to have a restrict regex or use some kind of javascript solution to reject invalid data at the source

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
