### ISSUE TITLE
Native scroll issue

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#560]
Reported by customer:
The plugin did not load the Google map with the native scroll,
touch, zoom features. Scroll was previously an issue the plugin had
to handle by overriding Google's functionality, but Google has
largely resolved this in their native implementation by disabling
scroll to zoom without pressing the command key. I would prefer to
use that.

**Comment by PerryRylance** [comment]
Google appear to have dropped ctrl + zoom and I unfortunately after many weeks of searching for a reason, trying to force gesture handling and asking if this feature has been removed, nothing has come up.

I think we can safely conclude that this feature is out of our control and has been dropped by Google, apologies to the customer in question.
