### ISSUE TITLE
Default marker image broken link in admin marker listing

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#562]
Admin default marker image in marker listings link to an image that doesn't exist

**Comment by PerryRylance** [comment]
Thanks @andtrev , could you elaborate a little?

This is on a practically fresh installation, I created a new map and then a new marker:

![image](https://user-images.githubusercontent.com/14136738/42573792-f83a4734-8514-11e8-98f4-977410efa793.png)
