### ISSUE TITLE
Comprehensive set of scoped events

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#573]
Follow the same pattern as dataTables, eg `init.wpgmza`

Here are some ideas:

init.wpgmza
boundschanged.wpgmza
zoomchanged.wpgmza
infowindowopen.wpgmza
infowindowclosed.wpgmza
markerlistingupdated.wpgmza
storelocatorresult.wpgmza
storelocatoraddressnotfound.wpgmza
categoryfilterchanged.wpgmza
directionschanged.wpgmza
markerfilterschanged.wpgmza

These should fire on BOTH the DOM element (this.element) AND on the map object itself.

**Comment by PerryRylance** [comment]
Another one to be dispatched by markers - userlocationproximity.wpgmza

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
