### ISSUE TITLE
Re-factor XML / DB code in wpgmaps.js

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#575]
There is a very large `if` / `else` block that does dozens of different tasks,

If marker pull is XML, this code is executed,

Else, the entirety of the code from the if block is copied and pasted into this else block.

This should be refactored as such:

1) Create a marker data object.

2) If marker pull is XML, populate the marker data object from there, else, populate the marker data object from passed localized data (wpgmaps_localize_marker_data)

3) Merge all the code from the old if / else block

This will simplify the code significantly

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
