### ISSUE TITLE
Auto "Night mode" theme

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#603]
Add a setting to allow for "auto night mode" so that the theme changes depending on the customers day/night time

**Comment by NickDuncanZA** [comment]
Example: https://www-lameva.barcelona.cat/santaeulalia/es/llumbcn (however this has a button on the map to switch to night mode)

**Comment by PerryRylance** [comment]
This should override any other themes during nighttime hours

Use the clients (JS) time to establish this
