### ISSUE TITLE
Improve the way settings are handled

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#611]
Current:

Each setting is explicitly set in an array from POST data

Better:

Each setting name is listed in an array so they can all be handled in a loop. Different loops need to be used for different input types

Best:

Use DOMDocument to scan for input, textarea and select elements, then you can loop over them and dynamically deal with the data  based on the control type. This eliminates the need to do anything at all in PHP when adding a new setting

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
