### ISSUE TITLE
Problems Adding and Deleting Circles in WPGM 7

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-google-maps#627]
Installed WPGM Plugins:

WP Google Maps 7.0.04
WP Google Maps Pro 7.08
WP Google Maps Gold 4.03
WP Google Maps VGM 3.00

The instructions for adding a Circle to a map are to click on the map. I click and nothing happens that I can see. I saved the map and when I reloaded the page there was a circle way out in the middle of the ocean. I clicked on the delete button on the Circles tab to remove that circle and nothing happened. Pretty much as described here: https://github.com/CodeCabin/wp-google-maps-pro/issues/594. Doc is on hold until this is figured out as I cannot take screenshots while this isn't working.

**Comment by PerryRylance** [comment]
@patdumond can you please try this again with 7.10.00 (from these repos)?

**Comment by patdumond** [comment]
Perry - I've tried this with the latest versions:

- Basic: 7.10.10
- Pro: 7.10.07
- Gold: 4.03

Still can't get the polygons (either circles or rectangles) to show up on the map where I placed them. Nor can I delete them once they've been saved.

**Comment by PerryRylance** [comment]
This was addressed a few versions again, thanks again to @andtrev
