### ISSUE TITLE
Problems Adding and Deleting Rectangles in WPGM 7

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-google-maps#628]
Installed WPGM Plugins:

WP Google Maps 7.0.04
WP Google Maps Pro 7.08
WP Google Maps Gold 4.03
WP Google Maps VGM 3.00

This is similar, but not identical, to GHI #627. However, with rectangles the rectangles appear on the map in the backend when I am editing the rectangle, but disappear from the map when I save the rectangles. The only time I can see them is when I am editing them, They do not delete when the delete button is clicked. Doc is on hold until this is figured out as I cannot take screenshots while this isn't working.

**Comment by patdumond** [comment]
Perry - I've tried this with the latest versions:

- Basic: 7.10.10
- Pro: 7.10.07
- Gold: 4.03

Still can't get the polygons (either circles or rectangles) to show up on the map where I placed them. Nor can I delete them once they've been saved.

**Comment by PerryRylance** [comment]
This was addressed a few versions back, many thanks to @andtrev
