### ISSUE TITLE
Bottleneck in wpGoogleMaps.php admin marker table

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#662]
This function should be implemented as an AJAX call instead of rendering every table row

This can break PHP when there is thousands of table rows, and it slows down the HTML parsing considerably.

**Comment by PerryRylance** [comment]
Use dataTables AJAX mechanism and an endpoint

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
