### ISSUE TITLE
Improve mobile UI/UX within the map editor

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#663]
This is something recently brought up on the forums. I think we would greatly benefit from revisiting this for users who may be making alterations via a mobile device.

**Comment by PerryRylance** [comment]
This will be a new feature in v8 - the current page will become the "legacy map editor" and the "modern map editor" will be an all-in-one page, with a fullscreen map, control bars and layers, similar to photoshop.

I doubt very much that there will be significant changes to the map edit page until then unless this becomes widespread. Please advise me if this becomes more of an issue, we can address it on a case by case basis until version 8, or re-open it if it becomes a common complaint
