### ISSUE TITLE
Yoast SEO Readability Issues

### ISSUE THREAD

**Issue by dylank6169** [CodeCabin/wp-google-maps#672]
Yoast SEO produces readability issues when the WPGM shortcode is added to a post/page. It uses the do_shortcode() function in the check and this is producing the following two errors specifically: 
- The text contains 3 consecutive sentences starting with the same word. Try to mix things up!
- x% of the sentences contain a transition word or phrase, which is less than the recommended minimum of 30%

**Comment by NickDuncanZA** [comment]
Massive amount of websites use Yoast and if they believe our plugin is causing SEO issues they will simply move on. This is high priority please.

**Comment by PerryRylance** [comment]
Looking into this now

**Comment by PerryRylance** [comment]
I'm waiting here https://github.com/Yoast/wordpress-seo/issues/8551 for them to reply

There is also a similar issue (closed) here https://github.com/Yoast/wordpress-seo/issues/7494

**Comment by PerryRylance** [comment]
I'm informed that any registered shortcodes will not be processed, confirmed that our shortcode is registered on the back end (according to JSM's Show Registered Shortcodes plugin)

**Comment by PerryRylance** [comment]
I'm making progress on this one and am now in contact with them

**Comment by dylank6169** [comment]
I have reopened this issue on Yoast, and waiting for a response from them, as it seems like it is still present in v9.1 of Yoast

**Comment by PerryRylance** [comment]
Thanks for the update @dylank6169 I'll reach out to them again if this is still ongoing

**Comment by PerryRylance** [comment]
This issue appears to have been solved - adding and removing the map makes no difference at all to the Yoast score for my test page.
