### ISSUE TITLE
DOMDocument not found

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#686]
This isn't technically a bug, but PHP can be built without DOMDocument support - I've seen this with 2 customers so far - just wanted it to be known that while DOMDocument is typically enabled by default, there are builds out there without it - this is especially true of "light" PHP builds which are widely available on Linux repository systems.

**Comment by PerryRylance** [comment]
Thanks for this, we'll look into potential shims or DOM libraries that don't depend on it
