### ISSUE TITLE
Ability to set mashup_ids to 'all' to select all maps dynamically

### ISSUE THREAD

**Issue by dylank6169** [CodeCabin/wp-google-maps#687]
User would like to have the ability to set the mashup_ids in the shortcode to 'all' to show all maps instead of having to add the IDs manually.

**Comment by PerryRylance** [comment]
This would be pretty straightforward, we can provide code for this, and it could be patched in for the next release

**Comment by dylank6169** [comment]
Agreed. I have provided the customer with the code and told him we will
look at adding this in a future release.

**Comment by PerryRylance** [comment]
Could this please be moved to the Pro repo

**Comment by DylanCodeCabin** [comment]
To be migrated to the internal repo (Pro V9.0.0)
