### ISSUE TITLE
Japanese translation files

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#704]
Please compare the attached translations and upload if it is more complete then the current translation

https://bleeper.io/app/ticket_uploads/8e7571b69ed079c33a3c1574d8a35253/0c1d0262fd1b1abd.po
https://bleeper.io/app/ticket_uploads/8e7571b69ed079c33a3c1574d8a35253/424d92f28a1a7bde.mo

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
