### ISSUE TITLE
Sort, check and token input on store locator radius

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#712]
The store locator radius setting is confusing some people

I propose we use a tokeninput here, commas to make numbering more clear, sort values on change, and don't allow zero / non-numeric values.

The pattern attribute would be a good workaround as a quicker solution

@StevenDeBeer please check out Token Input libraries and build one of them in, no need to re-invent the wheel.

http://loopj.com/jquery-tokeninput/

That one has always worked well for me, but I'm not sure if it allows "free tagging". Most Token Input libraries want to take a JSON source of allowed options, then offer an auto-suggest. We need one that allows "free tagging" so the user can enter numbers of their choice.

You may research and pick a library of your own choice, or use that one.

This should be sent off to the server as comma separated values to maintain compatibility.

Please change the save code to split those numbers on the comma, do a numeric sort, then implode them again before storing.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
