### ISSUE TITLE
installation via git has issues with gitignore

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#714]
From a user that is installing via git:

For your users who install the plugin via GIt (This is a common workflow at services like Pantheon.io),
there will be a problem.

There is a gitignore file in the folder js/v8 that prevents "wp-google-maps-pro.combined.js" from being pushed to the server. Without it, the Pro plugin won't work. It's pretty frustrating.

Once I removed them from your gitignore, and pushed to the server, the plugin was fine.

**Comment by PerryRylance** [comment]
We removed gitignore in favour of gitattributes a few versions back, so
this should be alright now

**Comment by dommermuth** [comment]
Thank you.  Sounds like you have a handle on it, but just so you know, I ran into this on a plugin purchased yesterday.

**Comment by PerryRylance** [comment]
Thank you Kurt, we'll double check the Pro add-on before closing this.

**Comment by PerryRylance** [comment]
I can confirm that .gitignore has been removed in the current releases and .gitattributes is now used to prevent diffs on the combined and minified files.

If anyone suffering this issue could please manually remove .gitignore, as updating the plugin will not solve this issue, that would be great.

If it would help anyone for us to add code to do remove .gitignore programatically, please let us know.
