### ISSUE TITLE
Zoom level solution for different screen sizes

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#720]
Don't implement this as screen size vs zoom level - this isn't an optimal way

Subject to testing, the absolute best thing to do would be to implement a "match bounds" zoom setting.

Record the viewport bounds when the map is saved.

At load time, pass the bounds to setBounds

This will ensure consistency access all screen sizes

**Comment by DylanCodeCabin** [comment]
Would be brilliant - To be moved to internal repo
