### ISSUE TITLE
Gutenberg JS breaking map on front end

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#735]
/js/v8/3rd-party-integration/gutenberg/dist/gutenberg.js

Right at the beginning this checks for window.wp but wp might be set on the front end, only the wp.editor will still not be set, this will cause the script to crash and stop the map from loading.

We should also check for !wp.editor

**Comment by PerryRylance** [comment]
Thank you @andtrev , I've implemented your suggestion!
