### ISSUE TITLE
jquery-cookie / js-cookie issue

### ISSUE THREAD

**Issue by stevengliebe** [CodeCabin/wp-google-maps#741]
Hello,

I'm seeing that the jquery-cookie.js file is enqueued with the 'jquery-cookie' handle. This is fine. The problem is that the contents of jquery-cookie.js are not actually jQuery Cookie. They're JavaScript Cookie, which is not just a newer version; it's a different script with different use.

This is creating conflicts with other plugins and themes that expect the old jQuery Cookie script to be enqueued as expected when using the 'jquery-cookie' handle. Can you please rename the handle (and file) to prevent conflicts like this?

Thank you.

**Comment by PerryRylance** [comment]
Hi Steven

Thank you very much for reporting this, we will be making this alteration and releasing a patch in the next few days.

Kind regards
- Perry

**Comment by stevengliebe** [comment]
Thank you. That will be helpful. I've seen a conflict in three different situations now.

**Comment by PerryRylance** [comment]
We've changed the handle to javascript-cookie in 7.10.51, which should be going out shortly, thanks again for letting us know!
