### ISSUE TITLE
InfoWindow content overflows out of InfoWindow when it is to large

### ISSUE THREAD

**Issue by dylank6169** [CodeCabin/wp-google-maps#743]
Would perhaps be good to add scrolling to the InfoWindow when the content is too large or auto-height.

**Comment by PerryRylance** [comment]
There should already be a scroll bar unless the theme overrides this, see the scrollFix class

Can you show me a site where this is an issue? There might be other things at play here

**Comment by PerryRylance** [comment]
No worries!
