### ISSUE TITLE
Allow HTML in shape infowindows

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#746]
Requested by user

> I would love to be able to place HTML into the polygon/polyline infoWindow. Currently it only supports the title. I tried to put HTML in but to get it working had to hack the core.js for pro.
> 
> To get it working in core.js on line 2965 I put in the following;

`var tmp_title = jQuery("<textarea/>").html(tmp_data['title']).text();</code>`

> And then replaced the instances of <code>tmp_data['title']</code> which followed with <code>tmp_title</code>.
> 
> Would be nice if the backend of poly(gon/line) have a Textarea for this HTML content.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
