### ISSUE TITLE
Tabs reinitializing map broken when not using modern store locator

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#754]
When reinitializing the map for a tab click, the modern store locator check isn't sufficient and will cause the script to fault and not load the map. This happens when not using the modern store locator so the element property is undefined.

line 277 of /wp-google-maps/js/wpgmaps.js

from:
if(MYMAP.modernStoreLocator)

to:
if(MYMAP.modernStoreLocator && MYMAP.modernStoreLocator.element)

**Comment by PerryRylance** [comment]
This should have been addressed - we're using a universal solution for handling tab clicks (and accordions etc.) which fires a resize event, rather than reinitialising the entire map.

If this does come up again please re-open
