### ISSUE TITLE
Info Windows "Carousel" not working, presented with error frontend 7.11.00

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-google-maps#770]
![capture](https://user-images.githubusercontent.com/41285248/51752011-079bbc80-20bf-11e9-99a3-41d67b6088c5.PNG)

**Comment by PerryRylance** [comment]
@StevenDeBeer I believe this is fixed, could you please correspond with me so we can re-test as I can't reproduce this
