### ISSUE TITLE
wp-api enqueues even on pages that don't use the map

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#774]
wp_enqueue_script('wp-api'); enqueues on pages without the map.

This has caused some issues with a customer's site, forcing JavaScript to load out of order and conflict with Ninja Forms from loading - on a page without any map.

**Comment by andtrev** [comment]
Another user has noticed this as well, WPGM causes several extra JS includes on their site on pages without a map - WP API, backbone and underscore.

**Comment by PerryRylance** [comment]
We no longer enqueue this file

All redundant JS files are gone in 8.1.0, the whole JS architecture is unified
