### ISSUE TITLE
markers appear and disappear when searching via store locator

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#783]
When searching via the store locator initially markers are displayed, then the search is submitted to the REST API and the results that come back cause some markers to disappear. It seems that there is something different about the radius calculations here in that markers on the edge are the ones disappearing.

**Comment by PerryRylance** [comment]
@andtrev Can you please let us know how to reproduce this one?

**Comment by andtrev** [comment]
Ah yes, I believe you fixed this issue already.  This was because the server and the front end were set differently between miles and kilometers.
