### ISSUE TITLE
Marker animations are not implemented for OpenLayers

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#786]

**Comment by PerryRylance** [comment]
Please implement setAnimation on WPGMZA.OLMarker

This should set a class name on the marker

You can add the animation for that classname in common.css

Please make sure these animations are reasonably close visually to their Google counterparts

**Comment by StevenDeBeer** [comment]
Animations were not being enqueued however a recent update appears to have corrected this.
