### ISSUE TITLE
country restriction broken for openlayers

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#791]
This appears to be an easy fix:

https://github.com/CodeCabin/wp-google-maps/blob/master/js/v8/open-layers/ol-geocoder.js#L60

the geocoder doesn't like the camel case with the data.countryCodes variable and will only recognize it when passed as data.countrycodes

**Comment by PerryRylance** [comment]
Thanks again @andtrev sorry this one came up again!

Fixed in 7.11.20 / Pro 7.11.24
