### ISSUE TITLE
Setting map height to percent breaks map in editor

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-google-maps#798]
A user has suggested setting a min-height to the map div on the admin edit page, as currently setting the map height to percent will make the map non-visible (height of 0) in the admin map editor.

**Comment by PerryRylance** [comment]
@StevenDeBeer I believe you implemented this already?

Please can you check that

- Your minimum height works *on the back end only*
- A warning is issued when the user selects 0% height
