### ISSUE TITLE
Pro Add-on plugin is not working

### ISSUE THREAD

**Issue by Tes3awy** [CodeCabin/wp-google-maps#821]
I have installed the WP Google Maps and added the Pro plugin but it's not working for some reason. I have also added the Google Maps API to see if it solves the problem but it doesn't.

Development Environment:
WordPress: 5.2.2
WP Google Maps Plugin: 7.11.35
WP Google Maps - Pro Add-on: 7.0.7
PHP: 7.3.x

**Comment by PerryRylance** [comment]
Hi there

Thank you for getting in touch.

You are through to the repository for the core plugin, if you need help with the Pro add-on, could we please ask you to [open a ticket](https://wpgmaps.com/contact-us) through our site.

At a glance, it looks like at some point you have been running the forked v7 beta, and have upgraded your basic plugin to the (non-forked) master v7. The two are not compatible.

Your options would be to roll back the basic plugin to the beta, or update to the master version of Pro.

If you'd like to do the latter, please open a ticket and we'll confirm proof of purchase there and get a download link out to you.

Kind regards
- Perry
