### ISSUE TITLE
Documentation inconsistency for Google Maps API key restrictions

### ISSUE THREAD

**Issue by DavidHepper** [CodeCabin/wp-google-maps#835]
The document at https://www.wpgmaps.com/documentation/creating-a-google-maps-api-key/ shows inconsistent examples of HTTP Referrers key restriction on the Google APIs page:

- `*yourdomain.com/*`  - should this be *.yourdomain... ?
- `*.sitegeeks.net`     - looks good but does not include the trailing `/*`
- `.*sitegeeks.net`     - ??

The placeholder text for this field on the Google page includes the `https://` prefix. Is this now required?

**Comment by PerryRylance** [comment]
Hi @DavidHepper 

`*yourdomain.com/*` is the correct format.

`*.yourdomain` will not match domains without a leading `www` (or other subdomain), such as `http://example.com`

We will remove the other items, thank you for pointing this out.

https:// is not required unless you wish to use user geolocation.

I hope that helps, if you feel we've missed anything then please feel free to re-open this issue.

Kind regards
- Perry
