### ISSUE TITLE
Map Data Shouldn't be loaded on every page. Should be DeQueued

### ISSUE THREAD

**Issue by frank6tg** [CodeCabin/wp-google-maps#861]
Example. See Waterfal https://gtmetrix.com/reports/sarasotakidsdocs.com/otsSNurd

There is No Map on any page except the contact page on this website yet the plugin loads a js file on EVERY page of the website. This file should be deqeued.

In this case the file is (I assume the number changes)

/wp-content/plugins/wp-google-maps/wpgmza_data-3864c0a86d2640fe5370e51d703514d4.js
--

**Comment by frank6tg** [comment]
Sorry to clarify this file shouldn't be loaded on every page of a WordPress site /wp-content/plugins/wp-google-maps/wpgmza_data.js?ver=5.3.2

**Comment by PerryRylance** [comment]
Hi @frank6tg 

We presently use this file to localize GDPR strings, and in the future this will be used to facilitate AJAX loading.

What we could do is only localize that file if GDPR is enabled, if that would help?

**Comment by frank6tg** [comment]
Yea, I like that solution!

Thanks!

Respectfully.

Frank Gomez
941-374-7711
Owner / Creative Director
Empowered Marketing, LLC (formerly Frank's Designs)
EmpoweredMarketingGroup.com
SustainableWP.com
WPTechGuru.com

Empowered Marketing® is trademarked by Frank Gomez

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
