### ISSUE TITLE
Change UI style to radio buttons with descriptions

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#869]

**Comment by PerryRylance** [comment]
Default - The default front end
Legacy - This setting is the same as Default, but provides options to change individual components to the modern style
Modern - Puts components inside the map, with pull-out panels
Compact - Puts all components and their labels inline
Minimal - The same as Compact, but with icons instead of text labels

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
