### ISSUE TITLE
Info-Window Image clipping (150x150) 

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#87]
All images will automatically use the 'thumbnail' dimensions from the WordPress media input. 

This is because we check if the thumbnail value is set, and use it regardless of whether the 'full' attribute is available for use. 

This is resolved by changing the following code within out media.js (wp-google-maps/js/media.js):

```
if (typeof wpgmza_img_thumbnail !== "undefined" && wpgmza_img_thumbnail.length > 0) {
   jQuery('#wpgmza_add_pic').val(wpgmza_img_thumbnail); 
} else { 
   jQuery('#wpgmza_add_pic').val(wpgmza_img_full); 
}
```

To this instead:

```
if (typeof wpgmza_img_full !== "undefined" && wpgmza_img_full.length > 0) {
    jQuery('#wpgmza_add_pic').val(wpgmza_img_full); 
} else { 
   jQuery('#wpgmza_add_pic').val(wpgmza_img_thumbnail); 
}
```

**Comment by NickDuncanZA** [comment]
Added in 6.3.14
