### ISSUE TITLE
ESRI Tile Server Support

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#877]
A client has requested support for this tile server. 

He motivates it by stating that it often has the most up to date aerial imagery since many states, counties and municipalities have their publicly accessible imagery hosted there.

**Comment by PerryRylance** [comment]
@DylanCodeCabin You can easily override the OpenLayers tile server, if he's happy using that engine, it's also reasonably easy to override for Google,

We'll definitely add this to the UI in 8.1.0

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
