### ISSUE TITLE
Fatal "The server failed to inflate the request" server error when loading data via AJAX

### ISSUE THREAD

**Issue by KZeni** [CodeCabin/wp-google-maps#891]
**- What's broken -**
https://www.bhc.edu/wp-json/wpgmza/v1/markers/base64ejyrvkrlzcljlvkyuqqoucpnlijptilrsoprmoxr0gejfgeugsskgylrsbvktqcv7hbn doesn't work & results in server error stating `The server failed to inflate the request`

**- What seems to work (rough/temporary workarouand) -**
https://www.bhc.edu/wp-json/wpgmza/v1/markers/?filter=%7b%22map_id%22%3a%221%22%2c%22mashup_ids%22%3a%5b%5d%7d works, and I had to manually replace `return function_exists('zlib_decode');` with `return false;` in the `isCompressedPathVariableSupported()` function (in **includes/class.rest-api.php**) as a temporary workaround for the issue.

**- Additional Testing & Results -**
This is breaking the map listing when WP Google Maps Pro 8.x is used, breaks the marker listing when editing a map, breaks the actual output of the map, and possibly breaks any/all other calls to the REST API (it seems.) I have the same version of this plugin used on other sites on the same hosting setup, and they're working perfectly fine (ex. https://www.greaterwausau.org/wp-json/wpgmza/v1/markers/base64eJyrVkrLzClJLVKyUqqOUcpNLIjPTIlRsopRMrSIUdIBiRRnlIIEi4Gi0bG1SrUAo5oQhQ.)

Not sure why https://www.greaterwausau.org/wp-json/wpgmza/v1/markers/base64eJyrVkrLzClJLVKyUqqOUcpNLIjPTIlRsopRMrSIUdIBiRRnlIIEi4Gi0bG1SrUAo5oQhQ would work while https://www.bhc.edu/wp-json/wpgmza/v1/markers/base64ejyrvkrlzcljlvkyuqqoucpnlijptilrsoprmoxr0gejfgeugsskgylrsbvktqcv7hbn doesn't (needing to manually disable compressed path setup to get https://www.bhc.edu/wp-json/wpgmza/v1/markers/?filter=%7b%22map_id%22%3a%221%22%2c%22mashup_ids%22%3a%5b%5d%7d) when both are on the same hosting.

**Comment by KZeni** [comment]
There was
```
// Make the WordPress URLs case-insensitive by way of defaulting to lowercase regardless of the input
function amperage_case_insensitive_url() {
	if (preg_match('/[A-Z]/', $_SERVER['REQUEST_URI']) && !is_admin()) {
		wp_redirect(strtolower(get_bloginfo('url').$_SERVER['REQUEST_URI']));
		exit;
	}
}
add_action('init', 'amperage_case_insensitive_url');
```
present in the theme's functions.php file on the problematic site. I'm guessing that's interfering with the compressed data data in the URL for REST API calls.

**Comment by KZeni** [comment]
The code above (https://github.com/CodeCabin/wp-google-maps/issues/891#issuecomment-602849722) was replaced with the following to prevent this issue:
```
// Add function for detecting if a query is a REST API call or not (building beyond what wp_is_json_request() provides. via: https://wordpress.stackexchange.com/a/317041/60913)
if ( !function_exists( 'is_rest' ) ) {
    /**
     * Checks if the current request is a WP REST API request.
     *
     * Case #1: After WP_REST_Request initialisation
     * Case #2: Support "plain" permalink settings
     * Case #3: It can happen that WP_Rewrite is not yet initialized,
     *          so do this (wp-settings.php)
     * Case #4: URL Path begins with wp-json/ (your REST prefix)
     *          Also supports WP installations in subfolders
     *
     * @returns boolean
     * @author matzeeable
     */
    function is_rest() {
        $prefix = rest_get_url_prefix( );
        if (defined('REST_REQUEST') && REST_REQUEST // (#1)
                || isset($_GET['rest_route']) // (#2)
                        && strpos( trim( $_GET['rest_route'], '\\/' ), $prefix , 0 ) === 0)
                return true;
        // (#3)
        global $wp_rewrite;
        if ($wp_rewrite === null) $wp_rewrite = new WP_Rewrite();

        // (#4)
        $rest_url = wp_parse_url( trailingslashit( rest_url( ) ) );
        $current_url = wp_parse_url( add_query_arg( array( ) ) );
        return strpos( $current_url['path'], $rest_url['path'], 0 ) === 0;
    }
}

// Make the WordPress URLs case-insensitive by way of defaulting to lowercase regardless of the input
function amperage_case_insensitive_url() {
	if (preg_match('/[A-Z]/', $_SERVER['REQUEST_URI']) && !is_admin() && !is_rest()) {
		wp_redirect(strtolower(get_bloginfo('url').$_SERVER['REQUEST_URI']));
		exit;
	}
}
add_action('init', 'amperage_case_insensitive_url');
```

**Comment by PerryRylance** [comment]
Hi @KZeni 

Thanks for this, it looks like this is specific to your theme, so it's not something we'd patch in the core code ideally,

If this does come up elsewhere, we can add a setting for this.

Thanks for your time in reporting this!

**Comment by KZeni** [comment]
Yup! Taken care of. Just wanted to put this out there for others if they happen to encounter this or something similar.
