### ISSUE TITLE
Many dense polygons cause loading errors

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-google-maps#895]
In some cases, calling the following functions may cause a website to crash due to resource limitations: 
- wpgmaps_b_admin_add_poly_javascript
- wpgmaps_b_admin_edit_poly_javascript

After debugging this it mainly occurs when: 
- The client has many densely populated polygons (potentially thousands of points per polygon)

Note: This does not crash the map editor page as it does not localize polygon data in the same way. 

It appears the functions mentioned above loop through each point manually, but only after splitting the data with string splitting functions which I imagine is not efficient in this case. 

**Quick fix for the client:** I ended up disabling the other polygons from being localized, this means only the polygon the user is editing currently is localized and the rest are ignored. This makes the loop more efficient, which allows us to get past the loading issue. 

**More permanent fix:** I believe we need to rebuild these polygon/polyline editors so that they either load this data after the page is loaded via ajax/rest or that we need to change the way we split/localize that data[.

**Comment by PerryRylance** [comment]
This is fixed in 8.1.0, in which all features are loaded via REST. Features can also be batch loaded.
