### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by arall** [CodeCabin/wp-google-maps#90]
I've found some potential XSS, SQL Injections and serval CSRF.

How should I report them?

**Comment by JarrydLong** [comment]
Hi arall. 

Please get in touch with us on http://www.wpgmaps.com/contact-us/ with further details so that we can address this immediately? 

Thank you very much for bringing this to our attention.

**Comment by NickDuncanZA** [comment]
Currently in progress with this.

All SQL queries are now prepared.

Outstanding: 
- All front end output must be escaped with functions such as esc_attr and esc_html
- Ensure security when creating XML files

-
