### ISSUE TITLE
Drop legacy global override

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#916]
It's unclear to me what exactly this does but it should be dropped

```
global $wpgmza_override;
$wpgmza_override = array();
```

In some contexts, it looks like this facilitates shortcode override parameters as well as GET overrides - this should be handled in `class.map.php` by respective maps

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
