### ISSUE TITLE
Drop wpgmza_path function

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#931]
I believe this function is used to stop backslashes accumulating when data is POSTed to the settings and map edit pages

8.1.0 handles this dynamically, this function is now redundant

If this function needs to be kept, recommend moving that to a well-named function on `Plugin` and creating an alias for the legacy name

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
