### ISSUE TITLE
Refactor `wpgmaps_tag_basic`

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#937]
I'd recommend creating a new `Shortcode` class which extends / uses `Factory`

That way the `Shortcode` creation can be overridden in Pro (eg to implement `ProShortcode`)

Older versions of Pro have their own function which takes care of this, so this should be safe to remove

The `Map` class itself should be given control over actually rendering the shortcode and it's constituent elements. `Map` can use it's own `StoreLocator`, `MarkerListing` and `DirectionsBox` rather than this functionality all being in a broad mix inside one function.

I'd recommend switching to an exclusively `DOMDocument` driven model here rather than working with raw HTML strings.

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
