### ISSUE TITLE
Drop wpgmaps_check_permissions and wpgmaps_permission_warning

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#943]
I'd recommend either re-implementing this system on `Plugin`, or dropping it completely

```
wpgmaps_check_permissions
wpgmaps_permission_warning
wpgmaps_marker_permission_check
```

If legacy Pro versions call these, move them onto the legacy Pro <= 8.1 file

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
