### ISSUE TITLE
Drop wpgmaps_update_db_check

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#944]
This function appears to have only one purpose, which is writing the temporary API key to the database.

This is now stored in `GoogleMapsLoader::TEMPORARY_API_KEY`

This function would appear to serve no purpose in Pro, however, I'd recommend checking Pro 6 to see if it's used there, and moving this to the legacy functions file if so

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
