### ISSUE TITLE
Refactor wpgmza_stats

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#948]
I believe calls to this were dropped during GDPR changes, however, if it's going to continue to be used, it should be moved to either `Plugin` if we anticipate it will store general stats, or, if it's going to continue just to log page visits to the plugin pages, it should be moved onto `Admin\UI`

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
