### ISSUE TITLE
Drop error logging functions

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#952]
The WP Google Maps error log was removed from the plugin quite some time ago, we should drop the following functions and prefer standard error reporting mechanisms instead.

```
wpgmza_return_error
wpgmza_write_to_error_log
wpgmza_error_directory
wpgmza_return_error_log
```

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
