### ISSUE TITLE
Refactor google_maps_api_key_warning

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#954]
This should really be implemented on a class of it's own

This function contains a mixture of content and logic (HTML / PHP) which should be separated. Recommend creating a new class which extends `DOMDocument`. The `Admin\UI` class should handle displaying it.

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
