### ISSUE TITLE
Drop wpgm_pro_link

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#957]
I've not seen any of our end users sites making use of the affiliate system at all, this should be safe to drop.

If it's desirable to keep this, I'd recommend re-implementing it on `Plugin`.

If this function is used in legacy versions of Pro, this will need to be moved into the Pro <= 8.1 functions file.

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
