### ISSUE TITLE
Pro: JS error in editor if description is empty on some hosts

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#96]
Some sites return a null value instead of an empty string. 

wp-google-maps-pro.php line 4814

var wpmgza_desc  = val.desc.replace(/\\/g, '');

change to:

if( val.desc !== null ){
    var wpmgza_desc  = val.desc.replace(/\\/g, '');
} else {
    var wpmgza_desc  = val.desc;
}

**Comment by NickDuncanZA** [comment]
Added to 6.3.13
Also added this for the marker title variable
