### ISSUE TITLE
Drop `wpgmza_widget` class

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#963]
This should either be re-implemented or aliased as `WPGMZA\Widget`, or delegated to `Plugin`

This file contains code which works with the maps table directly, this should be refactored to use `Map::createInstance`.

The HTML content and PHP logic for the widget setting panel should be separated, perhaps @Abelc01  could do this as he has some experience, should be a good refresher

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
