### ISSUE TITLE
Drop WPGMAPS_templates class

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#964]
The behaviour on this class is now handled in `Admin\UI`, the welcome and credits pages are now separate HTML and PHP, this file is now redundant.

I don't believe this file is used in Pro however checks should be done, this can be moved onto the Pro <= 8.1 legacy functions file if necessary.

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
