### ISSUE TITLE
Refactor admin-basic.js

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#967]
This file appears to have miscellaneous code for the map edit page in it, some of these functions are redundant with the new map editor

This code should be moved into `map-edit-page.js` on the `MapEditPage`'s prototype

The code which fits the map bounds to shapes will not work with OpenLayers and should be dropped or refactored, the buttons would need to be re-added

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
