### ISSUE TITLE
Consider removing jscolor.js

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#970]
This file in the least should be moved to /lib as it's a library script and not part of the plugin itself.

We should consider removing this completely and using the HTML5 color input, which is now widely supported.

If older versions of Pro reference this file, it may be necessary to retain it here, checks need to be carried out.

**Comment by DylanCodeCabin** [comment]
Closed as `stale` - Any and all refactoring to be evaluated after V9 release
