### ISSUE TITLE
Polygon fields not initially populated

### ISSUE THREAD

**Issue by Abelc01** [CodeCabin/wp-google-maps#973]
Polygon data will not be displayed when you edit a polygon .

replace line 185 in wp-google-maps-polygons.php:

 <p style='clear: both;' >Polygon dataa:<br /><textarea name=\"wpgmza_polygon\" id=\"poly_line_list\" style=\"height:100px; background-color:#FFF; padding:5px; overflow:auto;\"></textarea>

With:

 <p style='clear: both;' >Polygon dataa:<br /><textarea name=\"wpgmza_polygon\" id=\"poly_line_list\" style=\"height:100px; background-color:#FFF; padding:5px; overflow:auto;\">". $pol->polydata. "</textarea>

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
