### ISSUE TITLE
PRO :: MarkerListing::getRecords()

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#982]
In file `\wp-google-maps-pro\includes\marker-listings\class.marker-listing.php` the `getRecords()` method seems to have a bug.

Here's the code, for reference:

``` php
	public function getRecords($params)
	{
		global $wpdb;
		
		$result = Parent::getRecords($params);
		
		// TODO: Use MarkerFilter to populate marker listings, don't use query here. This is a hacky workaround, we should implement ORDER BY on MarkerFilter and use the marker filter to pull data for marker listings.
		foreach($result->data as $record)
		{
			if(!empty($record->icon))
				$record->icon = new MarkerIcon($record->icon);
			
			//$icon = new MarkerIcon($record->icon);
			//$record->icon = $icon->url;
			
			if(preg_match('/^\d+$/', $record->id))
				continue;
			
			preg_match('/\d+/', $record->id, $m);
			
			$qstr = "SELECT post_id FROM {$wpdb->prefix}postmeta WHERE meta_id = " . $m[0];
			$id = $wpdb->get_var($qstr);
			
			if(!$id)
				return;
			
			$record->link = get_permalink($id);
		}
		
		return apply_filters('wpgmza_marker_listing_markers', $result);
	}
```

It seems that `if(!$id) return;` should instead be `if(!$id) continue;`

**Comment by DylanCodeCabin** [comment]
Thanks for logging this! 

I need to compare the internal build code in the next week as we run up to V9 release. 

As mentioned here: 
- https://github.com/CodeCabin/wp-google-maps/issues/984

I may close and move this to our internal dev list as we take stock of this repo to clean up and improve comms with other developers moving forward, but it will be resolved by the time V9 is released to the public!

**Comment by DylanCodeCabin** [comment]
This has been moved to an internal repo, and my team will ensure this is resolved as part of the V9 build
