### ISSUE TITLE
Query::build()

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#983]
This is not processing the `groupBy` attribute. Currently it is:

``` php
			$where = $query->_where->toArray();
			if(!empty($where))
				$qstr .= " WHERE " . implode(' AND ', $where);
			
			$having = $query->_having->toArray();
			if(!empty($having))
				$qstr .= " HAVING " . implode(' AND ', $having);
```

And probably should be this:

``` php
			$where = $query->_where->toArray();
			if(!empty($where))
				$qstr .= " WHERE " . implode(' AND ', $where);

			$group = $query->_groupBy->toArray();
			if(!empty($group))
				$qstr .= " GROUP BY " . implode(', ', $group);
			
			$having = $query->_having->toArray();
			if(!empty($having))
				$qstr .= " HAVING " . implode(' AND ', $having);
```

**Comment by shazahm1** [comment]
@DylanCodeCabin 

As of WPGM version 8.1.20 (current of this post), this bug still exists.

And related...

\WPGMZA\Query has an `private $_orderBy;` that is not being processed in the `build()` method.

This:

``` PHP 
		
		if(!empty($this->_limit))
			$qstr .= " LIMIT {$this->_limit}";
		
		return $qstr;
```

should be this:

``` PHP
		$orderBy = $query->_orderBy->toArray();
		if(!empty($orderBy))
			$qstr .= " ORDER BY " . implode(', ', $orderBy);  
		
		if(!empty($this->_limit))
			$qstr .= " LIMIT {$this->_limit}";
		
		return $qstr;
```

Or perhaps something a little more intelligent to parse the fields to order by and the sort order flags (ASC|DESC).

**Comment by DylanCodeCabin** [comment]
Thank you for reconfirming @shazahm1 -> I'm reopening the issue and we'll get this sorted as soon as possible.

It does seem the processing here was only partially developed, I still need to confirm why that may have been, but as of now I don't see any reason why it shouldn't be fixed.

**Comment by DylanCodeCabin** [comment]
I've added the missing values and they are now supported by the method. 

Confirmed release date of `2022-06-20`

Thank you @shazahm1
