### ISSUE TITLE
PRO :: CategoryTree::createInstance()

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#984]
The filter does not pass the `$map` attribute. Currently, it is:

``` php
		if($override = apply_filters('wpgmza_create_WPGMZA\\CategoryTree', $override))
			return $override;
```

Please consider passing `$map` too. Like this:

``` php
		if($override = apply_filters('wpgmza_create_WPGMZA\\CategoryTree', $override, $map))
			return $override;
```

Why? This way the map object can be checked to see if an integration is active for the map and selectively override the category tree.

**Comment by DylanCodeCabin** [comment]
This has been moved to an internal repo, and my team will ensure this is resolved as part of the V9 build

**Comment by shazahm1** [comment]
@DylanCodeCabin 

Did the `$map` paremeter for the filter parameter make into the upcoming v9 release?

**Comment by DylanCodeCabin** [comment]
@shazahm1 

Yes, I'm happy to confirm it has been included in the release that will be going out, ideally, later today!
