### ISSUE TITLE
Database/XML pull method setting frontend

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-google-maps#988]
Whether the Database or XML pull method is selected and saved, XML will always be set to 1 and Database set to 0.

Tested with Basic only as well as Basic + Pro.

![image](https://user-images.githubusercontent.com/41285248/98512363-e2197c00-226e-11eb-933d-c32a832dc7d6.png)

**Comment by DylanCodeCabin** [comment]
@StevenDeBeer Both of those variables are simple 'constants' 

The setting for this is in `WPMGZA.settings` - One of these will be a number where `0` => `database` and `1` => `xml` that is where the constants are used.

The other version of the setting is a string:
![image](https://user-images.githubusercontent.com/16894783/98512677-610eb480-226f-11eb-9fa6-ec290cc6f7ee.png)

---
Varies between versions but this has existed for some time. 

Generally, anything on the root `WPGMZA` object is just a constant, not a setting.

**Comment by DylanCodeCabin** [comment]
Closed as `stale`
