### ISSUE TITLE
Function signature for DOMElement::remove does not match parent class (PHP 8)

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#991]
PHP 8 appears to implement `DOMElement::remove` natively, but it's implementation is different to `WPGMZA\DOMElement::remove`

I'm unsure if the difference is in the access (public, protected, private) or in the function arguments, or elsewhere, as the PHP documentation doesn't appear to reflect this change just yet, but PHP 8 is reporting that the definition for `WPGMZA\DOMElement::remove` does not match `DOMElement::remove`

Not present in PHP <= 7.4

Suggested fix would be to make the function definitions identical once documentation becomes available for this,

If that's not possible, a potential workaround would be to add a copy of `class.dom-element.php` with `remove` removed, and load this when PHP >= 8.0.0. Please note that in this instance, it would be necessary to check that the native implementation of `DOMElement::remove` has identical behaviour (and accessibility) as `WPGMZA\DOMElement::remove`

**Comment by PerryRylance** [comment]
See here https://bugs.php.net/bug.php?id=80494

**Comment by PerryRylance** [comment]
[Here's the fix I used](https://github.com/PerryRylance/DOMDocument/commit/cc178fc04e2fe8748ff094b27c268affb3a49e64) in my library. By implementing `__call` it's possible to add the `remove` behaviour there if the parent class doesn't implement it, or, if the parent class does, defer that behaviour to the parent class

**Comment by DylanCodeCabin** [comment]
Marked as `stale` - This was actually resolved down the line
