### ISSUE TITLE
WP5.6: "Show Points of Interest" setting fails

### ISSUE THREAD

**Issue by MatthewCodeCabin** [CodeCabin/wp-google-maps#995]
When you set this option to `unchecked` which is to **not** show points of interest  (e.g "Gold Reef City Theme Park"), it still shows the points of interest.

**Comment by DylanCodeCabin** [comment]
@MatthewCodeCabin Please confirm if this is WP5.6 related by setting up a second site with a version below 5.6 of WP

I want to prioritize big items on 5.6 so this may be a broader scope bug

**Comment by MatthewCodeCabin** [comment]
@DylanCodeCabin I have just tested this on `WP 5.5.3` and implementation on the **Backend** appears to be a broad scope bug, as this is also failing in `WP 5.5.3`.

However in for `WP 5.6`, both sides are failing - Backend and Frontend.

**Comment by DylanCodeCabin** [comment]
**Fixed in upcoming release candidate**
